site_name: journey
site_description: Journey App
repo_url: https://github.com/julionav/journey
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/julionav">julionav</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
